export const SUBSCRIPTIONS_DB = [
// === КИНО И ВИДЕО (15) ===
{ name: 'Яндекс Плюс', category: 'video', price: 299, logo: 'yandeks-plyus', domain: 'plus.yandex.ru', period: 'month' },
{ name: 'Иви', category: 'video', price: 399, logo: 'ivi', domain: 'ivi.ru', period: 'month' },
{ name: 'Кинопоиск HD', category: 'video', price: 199, logo: 'kinopoisk', domain: 'kinopoisk.ru', period: 'month' },
{ name: 'Okko', category: 'video', price: 399, logo: 'okko', domain: 'okko.tv', period: 'month' },
{ name: 'Premier', category: 'video', price: 299, logo: 'premier', domain: 'premier.one', period: 'month' },
{ name: 'Wink', category: 'video', price: 399, logo: 'wink', domain: 'wink.ru', period: 'month' },
{ name: 'Amediateka', category: 'video', price: 599, logo: 'amediateka', domain: 'amediateka.ru', period: 'month' },
{ name: 'KION', category: 'video', price: 0, logo: 'kion', domain: 'kion.ru', period: 'month' },
{ name: 'Море ТВ', category: 'video', price: 299, logo: 'more-tv', domain: 'more.tv', period: 'month' },
{ name: 'Триколор', category: 'video', price: 3600, logo: 'tricolor', domain: 'tricolor.tv', period: 'year' },
{ name: 'Start', category: 'video', price: 299, logo: 'start', domain: 'start.ru', period: 'month' },
{ name: 'Netflix', category: 'video', price: 0, logo: 'netflix', domain: 'netflix.com', period: 'month' },
{ name: 'Disney+', category: 'video', price: 0, logo: 'disney-plus', domain: 'disneyplus.com', period: 'month' },
{ name: 'Amazon Prime', category: 'video', price: 0, logo: 'amazon-prime', domain: 'amazon.com', period: 'month' },
{ name: 'YouTube Premium', category: 'video', price: 0, logo: 'youtube-music', domain: 'youtube.com', period: 'month' },
// === МУЗЫКА И АУДИО (8) ===
{ name: 'Яндекс Музыка', category: 'music', price: 199, logo: 'yandeks-muzyka', domain: 'music.yandex.ru', period: 'month' },
{ name: 'VK Музыка', category: 'music', price: 149, logo: 'vk-muzyka', domain: 'vk.com', period: 'month' },
{ name: 'Звук', category: 'music', price: 199, logo: 'zvuk', domain: 'zvuk.com', period: 'month' },
{ name: 'Apple Music', category: 'music', price: 169, logo: 'apple-music', domain: 'music.apple.com', period: 'month' },
{ name: 'Spotify', category: 'music', price: 0, logo: 'spotify', domain: 'spotify.com', period: 'month' },
{ name: 'MTS Music', category: 'music', price: 0, logo: 'mts-music', domain: 'mts.ru', period: 'month' },
{ name: 'YouTube Music', category: 'music', price: 0, logo: 'youtube-music', domain: 'music.youtube.com', period: 'month' },
{ name: 'Tidal', category: 'music', price: 0, logo: 'tidal', domain: 'tidal.com', period: 'month' },
// === КНИГИ И АУДИОКНИГИ (10) ===
{ name: 'Литрес', category: 'other', price: 0, logo: 'litres-podpiska', domain: 'litres.ru', period: 'month' },
{ name: 'MyBook', category: 'other', price: 0, logo: 'mybook', domain: 'mybook.ru', period: 'month' },
{ name: 'Букмейт', category: 'other', price: 0, logo: 'bukmeyt', domain: 'bukmeyt.ru', period: 'month' },
{ name: 'Storytel', category: 'other', price: 0, logo: 'storytel', domain: 'storytel.com', period: 'month' },
{ name: 'Патефон', category: 'other', price: 0, logo: 'podryad', domain: 'patefon.me', period: 'month' },
{ name: 'Литнет', category: 'other', price: 0, logo: 'loudplay', domain: 'litnet.com', period: 'month' },
{ name: 'Bookmate', category: 'other', price: 0, logo: 'mybook', domain: 'bookmate.com', period: 'month' },
{ name: 'Альпина.Книги', category: 'other', price: 0, logo: 'podryad', domain: 'alpinabook.ru', period: 'month' },
{ name: 'Ростелеком Книги', category: 'other', price: 0, logo: 'rostelecom', domain: 'rt.ru', period: 'month' },
{ name: 'Яндекс Книги', category: 'other', price: 0, logo: 'yandeks-plyus', domain: 'yandex.ru', period: 'month' },
// === ИНТЕРНЕТ ПРОВАЙДЕРЫ (25) ===
{ name: 'Ростелеком', category: 'internet', price: 450, logo: 'rostelecom', domain: 'rt.ru', period: 'month' },
{ name: 'МТС Домашний', category: 'internet', price: 400, logo: 'mts', domain: 'mts.ru', period: 'month' },
{ name: 'Дом.ру', category: 'internet', price: 750, logo: 'domru', domain: 'domru.ru', period: 'month' },
{ name: 'Билайн Интернет', category: 'internet', price: 450, logo: 'beeline', domain: 'beeline.ru', period: 'month' },
{ name: 'МегаФон', category: 'internet', price: 500, logo: 'megafon', domain: 'megafon.ru', period: 'month' },
{ name: 'Tele2', category: 'internet', price: 400, logo: 'tele2', domain: 'tele2.ru', period: 'month' },
{ name: 'Yota', category: 'internet', price: 400, logo: 'yota', domain: 'yota.ru', period: 'month' },
{ name: 'МГТС', category: 'internet', price: 450, logo: 'mgts', domain: 'mgts.ru', period: 'month' },
{ name: 'ТТК', category: 'internet', price: 400, logo: 'ttk', domain: 'ttk.ru', period: 'month' },
{ name: 'Онлайм', category: 'internet', price: 450, logo: 'onlaym', domain: 'onlime.ru', period: 'month' },
{ name: 'Уфанет', category: 'internet', price: 400, logo: 'ufanet', domain: 'ufanet.ru', period: 'month' },
{ name: 'SkyNet', category: 'internet', price: 400, logo: 'skynet', domain: 'skynt.ru', period: 'month' },
{ name: 'Сибирские сети', category: 'internet', price: 350, logo: 'sibirskie-seti', domain: '211.ru', period: 'month' },
{ name: 'Зелёная точка', category: 'internet', price: 350, logo: 'zelenaya-tochka', domain: 'zelenaya.net', period: 'month' },
{ name: 'Интерсвязь', category: 'internet', price: 400, logo: 'intersvyaz', domain: 'intersvyaz.ru', period: 'month' },
{ name: 'Инфолинк', category: 'internet', price: 400, logo: 'infolink', domain: 'infolink.ru', period: 'month' },
{ name: 'NetByNet', category: 'internet', price: 450, logo: 'netbynet', domain: 'netbynet.ru', period: 'month' },
{ name: 'Акадо', category: 'internet', price: 450, logo: 'akado', domain: 'akado.ru', period: 'month' },
{ name: 'QWERTY', category: 'internet', price: 450, logo: 'qwerty', domain: 'qwerty.ru', period: 'month' },
{ name: 'Реал', category: 'internet', price: 400, logo: 'real', domain: 'real.ru', period: 'month' },
{ name: 'GoodLine', category: 'internet', price: 450, logo: 'good-line', domain: 'goodline.ru', period: 'month' },
{ name: 'Миранда Медиа', category: 'internet', price: 400, logo: 'miranda-media', domain: 'miranda-media.ru', period: 'month' },
{ name: 'ВестКолл', category: 'internet', price: 450, logo: 'podryad', domain: 'westcall.ru', period: 'month' },
{ name: 'Starlink', category: 'internet', price: 0, logo: 'podryad', domain: 'starlink.com', period: 'month' },
{ name: 'Омские кабельные сети', category: 'internet', price: 400, logo: 'omskie-kabelnye-seti', domain: 'omskic.ru', period: 'month' },
// === СОТОВЫЕ ОПЕРАТОРЫ (12) ===
{ name: 'МТС', category: 'mobile', price: 300, logo: 'mts', domain: 'mts.ru', period: 'month' },
{ name: 'Билайн', category: 'mobile', price: 300, logo: 'beeline', domain: 'beeline.ru', period: 'month' },
{ name: 'МегаФон', category: 'mobile', price: 300, logo: 'megafon', domain: 'megafon.ru', period: 'month' },
{ name: 'Tele2', category: 'mobile', price: 250, logo: 'tele2', domain: 'tele2.ru', period: 'month' },
{ name: 'Yota', category: 'mobile', price: 400, logo: 'yota', domain: 'yota.ru', period: 'month' },
{ name: 'Т-Мобайл', category: 'mobile', price: 200, logo: 't2', domain: 't-mobile.ru', period: 'month' },
{ name: 'СберМобайл', category: 'mobile', price: 200, logo: 'sber', domain: 'sbermobile.ru', period: 'month' },
{ name: 'Ростелеком Мобильный', category: 'mobile', price: 250, logo: 'rostelecom', domain: 'rt.ru', period: 'month' },
{ name: 'Дом.ру Мобильный', category: 'mobile', price: 250, logo: 'domru', domain: 'domru.ru', period: 'month' },
{ name: 'Virgin Mobile', category: 'mobile', price: 200, logo: 'podryad', domain: 'virginmobile.ru', period: 'month' },
{ name: 'MCN Telecom', category: 'mobile', price: 0, logo: 'mts', domain: 'mcntelecom.ru', period: 'month' },
{ name: 'Алло Инкогнито', category: 'mobile', price: 0, logo: 'podryad', domain: 'allo-incognito.ru', period: 'month' },
// === БАНКОВСКИЕ ПОДПИСКИ (15) ===
{ name: 'Т-Банк Pro', category: 'bank', price: 299, logo: 'tbank', domain: 'tbank.ru', period: 'month' },
{ name: 'Т-Банк Premium', category: 'bank', price: 1990, logo: 'tbank-premium', domain: 'tbank.ru', period: 'month' },
{ name: 'СберПрайм', category: 'bank', price: 199, logo: 'sberpraym', domain: 'sber.ru', period: 'month' },
{ name: 'Альфа-Смарт', category: 'bank', price: 299, logo: 'alfa-smart', domain: 'alfabank.ru', period: 'month' },
{ name: 'Альфа-Премиум', category: 'bank', price: 0, logo: 'alfa', domain: 'alfabank.ru', period: 'month' },
{ name: 'ВТБ Привилегия', category: 'bank', price: 0, logo: 'vtb-privilegiya', domain: 'vtb.ru', period: 'month' },
{ name: 'Газпромбанк Premium', category: 'bank', price: 0, logo: 'gazprombank-premium', domain: 'gazprombank.ru', period: 'month' },
{ name: 'Райффайзен Premium', category: 'bank', price: 0, logo: 'raiffayzen-premium', domain: 'raiffeisen.ru', period: 'month' },
{ name: 'Росбанк Premium', category: 'bank', price: 0, logo: 'podryad', domain: 'rosbank.ru', period: 'month' },
{ name: 'Открытие Premium', category: 'bank', price: 0, logo: 'podryad', domain: 'open.ru', period: 'month' },
{ name: 'Почта Банк Premium', category: 'bank', price: 0, logo: 'podryad', domain: 'pochtabank.ru', period: 'month' },
{ name: 'Уралсиб Premium', category: 'bank', price: 0, logo: 'podryad', domain: 'uralsib.ru', period: 'month' },
{ name: 'Ак Барс Premium', category: 'bank', price: 0, logo: 'podryad', domain: 'akbars.ru', period: 'month' },
{ name: 'Совкомбанк Premium', category: 'bank', price: 0, logo: 'podryad', domain: 'sovcombank.ru', period: 'month' },
{ name: 'Home Credit Premium', category: 'bank', price: 0, logo: 'podryad', domain: 'homecredit.ru', period: 'month' },
// === ОБЛАЧНЫЕ ХРАНИЛИЩА (12) ===
{ name: 'Яндекс Диск 100ГБ', category: 'other', price: 0, logo: 'yandeksdisk-100gb', domain: 'disk.yandex.ru', period: 'month' },
{ name: 'Яндекс Диск 1ТБ', category: 'other', price: 0, logo: 'yandeksdisk-1tb', domain: 'disk.yandex.ru', period: 'month' },
{ name: 'Облако Mail.ru 64ГБ', category: 'other', price: 0, logo: 'oblako-mailru-64gb', domain: 'cloud.mail.ru', period: 'month' },
{ name: 'iCloud 50ГБ', category: 'other', price: 0, logo: 'icloud-50gb', domain: 'icloud.com', period: 'month' },
{ name: 'iCloud 200ГБ', category: 'other', price: 0, logo: 'icloud-200gb', domain: 'icloud.com', period: 'month' },
{ name: 'iCloud 2ТБ', category: 'other', price: 0, logo: 'icloud-2tb', domain: 'icloud.com', period: 'month' },
{ name: 'Google One 100ГБ', category: 'other', price: 0, logo: 'google-one-100gb', domain: 'one.google.com', period: 'month' },
{ name: 'Google One 2ТБ', category: 'other', price: 0, logo: 'google-one-2tb', domain: 'one.google.com', period: 'month' },
{ name: 'OneDrive 100ГБ', category: 'other', price: 0, logo: 'onedrive-100gb', domain: 'onedrive.live.com', period: 'month' },
{ name: 'Dropbox 2ТБ', category: 'other', price: 0, logo: 'dropbox-2tb', domain: 'dropbox.com', period: 'month' },
{ name: 'СберДиск', category: 'other', price: 0, logo: 'sber', domain: 'sber.ru', period: 'month' },
{ name: 'VK WorkDisk', category: 'other', price: 0, logo: 'vk', domain: 'vk.com', period: 'month' },
// === ИГРОВЫЕ ПОДПИСКИ (12) ===
{ name: 'PlayStation Plus', category: 'games', price: 699, logo: 'playstation-plus', domain: 'playstation.com', period: 'month' },
{ name: 'Xbox Game Pass', category: 'games', price: 599, logo: 'xbox-game-pass', domain: 'xbox.com', period: 'month' },
{ name: 'EA Play', category: 'games', price: 0, logo: 'podryad', domain: 'ea.com', period: 'month' },
{ name: 'Discord Nitro', category: 'games', price: 599, logo: 'discord', domain: 'discord.com', period: 'month' },
{ name: 'Twitch Turbo', category: 'games', price: 0, logo: 'twich', domain: 'twitch.tv', period: 'month' },
{ name: 'Nintendo Online', category: 'games', price: 0, logo: 'nintendo-online', domain: 'nintendo.com', period: 'month' },
{ name: 'GeForce NOW', category: 'games', price: 0, logo: 'geforce-now', domain: 'nvidia.com', period: 'month' },
{ name: 'Steam', category: 'games', price: 0, logo: 'steam', domain: 'steampowered.com', period: 'month' },
{ name: 'Ubisoft+', category: 'games', price: 0, logo: 'ubisoft', domain: 'ubisoft.com', period: 'month' },
{ name: 'Humble Choice', category: 'games', price: 0, logo: 'podryad', domain: 'humblebundle.com', period: 'month' },
{ name: 'itch.io', category: 'games', price: 0, logo: 'podryad', domain: 'itch.io', period: 'month' },
{ name: 'Epic Games', category: 'games', price: 0, logo: 'podryad', domain: 'epicgames.com', period: 'month' },
// === ОБРАЗОВАНИЕ (30) ===
{ name: 'Skillbox', category: 'education', price: 0, logo: 'skillbox', domain: 'skillbox.ru', period: 'month' },
{ name: 'GeekBrains', category: 'education', price: 0, logo: 'geekbrains', domain: 'geekbrains.ru', period: 'month' },
{ name: 'Нетология', category: 'education', price: 0, logo: 'netologiya', domain: 'netology.ru', period: 'month' },
{ name: 'Stepik', category: 'education', price: 0, logo: 'stepik', domain: 'stepik.org', period: 'month' },
{ name: 'SkillFactory', category: 'education', price: 0, logo: 'podryad', domain: 'skillfactory.ru', period: 'month' },
{ name: 'Яндекс Практикум', category: 'education', price: 0, logo: 'yandekspraktikum', domain: 'practicum.yandex.ru', period: 'month' },
{ name: 'Skyeng', category: 'education', price: 0, logo: 'skyeng', domain: 'skyeng.ru', period: 'month' },
{ name: 'Skypro', category: 'education', price: 0, logo: 'skyyeng', domain: 'skypro.ru', period: 'month' },
{ name: 'OTUS', category: 'education', price: 0, logo: 'podryad', domain: 'otus.ru', period: 'month' },
{ name: 'HTML Academy', category: 'education', price: 0, logo: 'podryad', domain: 'htmlacademy.ru', period: 'month' },
{ name: 'Loftschool', category: 'education', price: 0, logo: 'loftschool', domain: 'loftschool.com', period: 'month' },
{ name: 'GeekUniversity', category: 'education', price: 0, logo: 'geekbrains', domain: 'geekuniversity.ru', period: 'month' },
{ name: 'Coding Factory', category: 'education', price: 0, logo: 'podryad', domain: 'codingfactory.ru', period: 'month' },
{ name: 'Teletype', category: 'education', price: 0, logo: 'teletype', domain: 'teletype.in', period: 'month' },
{ name: 'Contented', category: 'education', price: 0, logo: 'podryad', domain: 'contented.ru', period: 'month' },
{ name: 'Lingualeo', category: 'education', price: 0, logo: 'lingualeo', domain: 'lingualeo.com', period: 'month' },
{ name: 'Duolingo Plus', category: 'education', price: 0, logo: 'duolingo-plus', domain: 'duolingo.com', period: 'month' },
{ name: 'Puzzle English', category: 'education', price: 0, logo: 'puzzle-english', domain: 'puzzle-english.com', period: 'month' },
{ name: 'EnglishDom', category: 'education', price: 0, logo: 'podryad', domain: 'englishdom.com', period: 'month' },
{ name: 'Tilda Publishing', category: 'education', price: 0, logo: 'tilda', domain: 'tilda.cc', period: 'month' },
{ name: 'Синхронизация', category: 'education', price: 0, logo: 'podryad', domain: 'sync.ru', period: 'month' },
{ name: 'Постнаука', category: 'education', price: 0, logo: 'podryad', domain: 'postnauka.ru', period: 'month' },
{ name: 'Арзамас', category: 'education', price: 0, logo: 'podryad', domain: 'arzamas.academy', period: 'month' },
{ name: 'Magisteria', category: 'education', price: 0, logo: 'podryad', domain: 'magisteria.ru', period: 'month' },
{ name: '4brain', category: 'education', price: 0, logo: 'podryad', domain: '4brain.ru', period: 'month' },
{ name: 'GetCourse', category: 'education', price: 0, logo: 'podryad', domain: 'getcourse.ru', period: 'month' },
{ name: 'Antitraining', category: 'education', price: 0, logo: 'podryad', domain: 'antitraining.ru', period: 'month' },
{ name: 'Zenclass', category: 'education', price: 0, logo: 'podryad', domain: 'zenclass.ru', period: 'month' },
{ name: 'SOHO.LMS', category: 'education', price: 0, logo: 'podryad', domain: 'soho-lms.ru', period: 'month' },
{ name: 'Skillspace', category: 'education', price: 0, logo: 'podryad', domain: 'skillspace.ru', period: 'month' },
// === ДОСТАВКА ЕДЫ (15) ===
{ name: 'Яндекс Еда', category: 'delivery', price: 0, logo: 'yandeks-lavka', domain: 'eda.yandex.ru', period: 'month' },
{ name: 'Delivery Club', category: 'delivery', price: 0, logo: 'podryad', domain: 'deliveryclub.ru', period: 'month' },
{ name: 'Самокат', category: 'delivery', price: 0, logo: 'samokat', domain: 'samokat.ru', period: 'month' },
{ name: 'Яндекс Лавка', category: 'delivery', price: 0, logo: 'yandeks-lavka', domain: 'lavka.yandex.ru', period: 'month' },
{ name: 'СберМаркет', category: 'delivery', price: 0, logo: 'sber', domain: 'sbermarket.ru', period: 'month' },
{ name: 'ВкусВилл', category: 'delivery', price: 0, logo: 'podryad', domain: 'vkusvill.ru', period: 'month' },
{ name: 'OZON Fresh', category: 'delivery', price: 0, logo: 'ozon-premium', domain: 'ozon.ru', period: 'month' },
{ name: 'Пятёрочка', category: 'delivery', price: 0, logo: 'podryad', domain: '5post.ru', period: 'month' },
{ name: 'Перекрёсток Впрок', category: 'delivery', price: 0, logo: 'podryad', domain: 'perekrestok.ru', period: 'month' },
{ name: 'Лента', category: 'delivery', price: 0, logo: 'lanta', domain: 'lenta.com', period: 'month' },
{ name: 'Магнит', category: 'delivery', price: 0, logo: 'mamba-vip', domain: 'magnit.ru', period: 'month' },
{ name: 'Ашан', category: 'delivery', price: 0, logo: 'podryad', domain: 'auchan.ru', period: 'month' },
{ name: 'Метро', category: 'delivery', price: 0, logo: 'podryad', domain: 'metro.ru', period: 'month' },
{ name: 'iHerb', category: 'delivery', price: 0, logo: 'podryad', domain: 'iherb.com', period: 'month' },
{ name: 'AliExpress', category: 'delivery', price: 0, logo: 'aliexpress-premium', domain: 'aliexpress.ru', period: 'month' },
// === ПОДПИСКА НА ЕДУ (20) ===
{ name: 'Level Kitchen', category: 'delivery', price: 0, logo: 'level-kitchen', domain: 'levelkitchen.com', period: 'month' },
{ name: 'Grow Food', category: 'delivery', price: 0, logo: 'grow-food', domain: 'growfood.pro', period: 'month' },
{ name: 'BeFit', category: 'delivery', price: 0, logo: 'podryad', domain: 'befit-food.ru', period: 'month' },
{ name: 'JustFood', category: 'delivery', price: 0, logo: 'podryad', domain: 'justfood.pro', period: 'month' },
{ name: 'My Food', category: 'delivery', price: 0, logo: 'podryad', domain: 'myfood.ru', period: 'month' },
{ name: 'Performance Food', category: 'delivery', price: 0, logo: 'podryad', domain: 'performance-food.ru', period: 'month' },
{ name: 'Ideal Day', category: 'delivery', price: 0, logo: 'podryad', domain: 'idealday.ru', period: 'month' },
{ name: 'Smart Calories', category: 'delivery', price: 0, logo: 'podryad', domain: 'smartcalories.ru', period: 'month' },
{ name: 'ВкусМил', category: 'delivery', price: 0, logo: 'podryad', domain: 'vkusvill.ru', period: 'month' },
{ name: 'ПриЕм', category: 'delivery', price: 0, logo: 'podryad', domain: 'priem-food.ru', period: 'month' },
{ name: 'Шефмаркет', category: 'delivery', price: 0, logo: 'podryad', domain: 'chefmarket.ru', period: 'month' },
{ name: 'Польза', category: 'delivery', price: 0, logo: 'podryad', domain: 'polza-food.ru', period: 'month' },
{ name: 'Elementaree', category: 'delivery', price: 0, logo: 'podryad', domain: 'elementaree.ru', period: 'month' },
{ name: 'Foodband', category: 'delivery', price: 0, logo: 'podryad', domain: 'foodband.ru', period: 'month' },
{ name: '2Берега', category: 'delivery', price: 0, logo: 'podryad', domain: '2beregaf.ru', period: 'month' },
{ name: 'Fresh Lab', category: 'delivery', price: 0, logo: 'podryad', domain: 'freshlab.ru', period: 'month' },
{ name: 'Kitchen Republic', category: 'delivery', price: 0, logo: 'podryad', domain: 'kitchenrepublic.ru', period: 'month' },
{ name: 'Yandex Food Pro', category: 'delivery', price: 0, logo: 'yandeks-lavka', domain: 'eda.yandex.ru', period: 'month' },
{ name: 'Delivery Club подписка', category: 'delivery', price: 0, logo: 'podryad', domain: 'deliveryclub.ru', period: 'month' },
{ name: 'Mr. Doors Food', category: 'delivery', price: 0, logo: 'podryad', domain: 'mrdoorsfood.ru', period: 'month' },
// === ФИТНЕС КЛУБЫ (25) ===
{ name: 'World Class', category: 'fitness', price: 5000, logo: 'world-class', domain: 'worldclass.ru', period: 'month' },
{ name: 'DDX Fitness', category: 'fitness', price: 1700, logo: 'pure-fitness', domain: 'ddxfitness.ru', period: 'month' },
{ name: 'X-Fit', category: 'fitness', price: 3000, logo: 'podryad', domain: 'xfit.ru', period: 'month' },
{ name: 'Планета Фитнес', category: 'fitness', price: 0, logo: 'planeta-fitnes', domain: 'fitness.ru', period: 'month' },
{ name: 'Зебра Фитнес', category: 'fitness', price: 0, logo: 'zebra', domain: 'fitnes-zebra.ru', period: 'month' },
{ name: 'Spirit Fitness', category: 'fitness', price: 0, logo: 'sss-fitness', domain: 'spiritfitness.ru', period: 'month' },
{ name: 'URBANFIT', category: 'fitness', price: 0, logo: 'sss-fitness', domain: 'urbanfit.ru', period: 'month' },
{ name: 'Alex Fitness', category: 'fitness', price: 0, logo: 'alex-fitness', domain: 'alexfitness.ru', period: 'month' },
{ name: 'Фитнес-Прага', category: 'fitness', price: 0, logo: 'fitnes-praga', domain: 'fitness-praga.ru', period: 'month' },
{ name: 'ССЗ Fitness', category: 'fitness', price: 0, logo: 'sss-fitness', domain: 'sszfitness.ru', period: 'month' },
{ name: 'Pure Fitness', category: 'fitness', price: 0, logo: 'pure-vip', domain: 'purefitness.ru', period: 'month' },
{ name: 'Encore Fitness', category: 'fitness', price: 0, logo: 'podryad', domain: 'encorefitness.ru', period: 'month' },
{ name: 'Republika', category: 'fitness', price: 0, logo: 'podryad', domain: 'republika.ru', period: 'month' },
{ name: 'Физкульт', category: 'fitness', price: 0, logo: 'podryad', domain: 'fizkult.ru', period: 'month' },
{ name: 'SSC', category: 'fitness', price: 0, logo: 'sss-fitness', domain: 'sscfitness.ru', period: 'month' },
{ name: 'Fitnes Factory', category: 'fitness', price: 0, logo: 'sss-fitness', domain: 'fitnessfactory.ru', period: 'month' },
{ name: 'FitCurves', category: 'fitness', price: 0, logo: 'sss-fitness', domain: 'fitcurves.ru', period: 'month' },
{ name: 'Orange Fitness', category: 'fitness', price: 0, logo: 'podryad', domain: 'orangefitness.ru', period: 'month' },
{ name: 'Top Fitness', category: 'fitness', price: 0, logo: 'podryad', domain: 'topfitness.ru', period: 'month' },
{ name: 'Fitness Place', category: 'fitness', price: 0, logo: 'podryad', domain: 'fitnessplace.ru', period: 'month' },
{ name: 'Gymnasium', category: 'fitness', price: 0, logo: 'podryad', domain: 'gymnasium.ru', period: 'month' },
{ name: 'UFC GYM', category: 'fitness', price: 0, logo: 'podryad', domain: 'ufcgym.ru', period: 'month' },
{ name: 'Adidas Fitness', category: 'fitness', price: 0, logo: 'podryad', domain: 'adidas.ru', period: 'month' },
{ name: 'Reebok Fitness', category: 'fitness', price: 0, logo: 'podryad', domain: 'reebok.ru', period: 'month' },
{ name: 'Fitnes Прага', category: 'fitness', price: 0, logo: 'fitnes-praga', domain: 'fitness-praga.ru', period: 'month' },
// === ЖКХ И ДОМОФОНЫ (15) ===
{ name: 'Домофон Цифрал', category: 'other', price: 50, logo: 'seven-sky', domain: 'cyfral-group.ru', period: 'month' },
{ name: 'Seven Sky', category: 'other', price: 0, logo: 'seven-sky', domain: '7sky.ru', period: 'month' },
{ name: 'Метаком', category: 'other', price: 0, logo: 'podryad', domain: 'metacom.ru', period: 'month' },
{ name: 'Vizit', category: 'other', price: 0, logo: 'vedomosti', domain: 'vizit.ru', period: 'month' },
{ name: 'Eltis', category: 'other', price: 0, logo: 'podryad', domain: 'eltis.ru', period: 'month' },
{ name: 'Факториал', category: 'other', price: 0, logo: 'podryad', domain: 'factorial.ru', period: 'month' },
{ name: 'Домофон.ру', category: 'other', price: 0, logo: 'domovenok', domain: 'domofon.ru', period: 'month' },
{ name: 'АйТеко', category: 'other', price: 0, logo: 'podryad', domain: 'aiteco.ru', period: 'month' },
{ name: 'Ником', category: 'other', price: 0, logo: 'podryad', domain: 'nikom.ru', period: 'month' },
{ name: 'Tantos', category: 'other', price: 0, logo: 'podryad', domain: 'tantos.ru', period: 'month' },
{ name: 'Умный Дом.ру', category: 'other', price: 200, logo: 'mts-tv', domain: 'domru.ru', period: 'month' },
{ name: 'Яндекс Станция', category: 'other', price: 0, logo: 'yandeks-plyus', domain: 'yandex.ru', period: 'month' },
{ name: 'VK Капсула', category: 'other', price: 0, logo: 'vk', domain: 'vk.com', period: 'month' },
{ name: 'Сбер Умный дом', category: 'other', price: 0, logo: 'sber', domain: 'sber.ru', period: 'month' },
{ name: 'Rubek', category: 'other', price: 0, logo: 'podryad', domain: 'rubek.ru', period: 'month' },
// === ОХРАНА И БЕЗОПАСНОСТЬ (12) ===
{ name: 'Дельта Охрана', category: 'security', price: 0, logo: 'delta-okhrana', domain: 'delta.ru', period: 'month' },
{ name: 'Гольфстрим', category: 'security', price: 0, logo: 'golfstrim', domain: 'gulfstream.ru', period: 'month' },
{ name: 'Цезарь Сателлит', category: 'security', price: 0, logo: 'podryad', domain: 'caesar.ru', period: 'month' },
{ name: 'Росгвардия', category: 'security', price: 0, logo: 'podryad', domain: 'rosguard.gov.ru', period: 'month' },
{ name: 'Атлант', category: 'security', price: 0, logo: 'podryad', domain: 'atlant.ru', period: 'month' },
{ name: 'Вояж', category: 'security', price: 0, logo: 'podryad', domain: 'voyage.ru', period: 'month' },
{ name: 'Титан', category: 'security', price: 0, logo: 'podryad', domain: 'titan.ru', period: 'month' },
{ name: 'ЖилАльянс', category: 'security', price: 0, logo: 'podryad', domain: 'zhilalians.ru', period: 'month' },
{ name: 'Dr.Web', category: 'security', price: 1200, logo: 'podryad', domain: 'drweb.ru', period: 'year' },
{ name: 'Касперский', category: 'security', price: 0, logo: 'kaspersky', domain: 'kaspersky.ru', period: 'year' },
{ name: 'ESET', category: 'security', price: 0, logo: 'podryad', domain: 'eset.com', period: 'year' },
{ name: 'Avast Premium', category: 'security', price: 0, logo: 'podryad', domain: 'avast.com', period: 'year' },
// === ПАРКОВКИ И АВТО (15) ===
{ name: 'Парковки Москвы', category: 'auto', price: 0, logo: 'platnye-parkovki', domain: 'parking.mos.ru', period: 'month' },
{ name: 'Штрафы ГИБДД', category: 'auto', price: 0, logo: 'shtrafy-gibdd', domain: 'gibdd.ru', period: 'month' },
{ name: 'Автотека', category: 'auto', price: 0, logo: 'avtoteka', domain: 'avtoteka.ru', period: 'month' },
{ name: 'BelkaCar', category: 'auto', price: 0, logo: 'belkacar', domain: 'belkacar.ru', period: 'month' },
{ name: 'Делимобиль', category: 'auto', price: 0, logo: 'delimobil-prime', domain: 'delimobil.ru', period: 'month' },
{ name: 'Яндекс.Драйв', category: 'auto', price: 0, logo: 'yandeksdrayv-plus', domain: 'drive.yandex.ru', period: 'month' },
{ name: 'Парковки СПб', category: 'auto', price: 0, logo: 'platnye-parkovki', domain: 'parking.spb.ru', period: 'month' },
{ name: 'Парковки Казани', category: 'auto', price: 0, logo: 'platnye-parkovki', domain: 'kzn.ru', period: 'month' },
{ name: 'Парковки Краснодара', category: 'auto', price: 0, logo: 'platnye-parkovki', domain: 'krd.ru', period: 'month' },
{ name: 'Парковки Тюмени', category: 'auto', price: 0, logo: 'platnye-parkovki', domain: 'tyumen.ru', period: 'month' },
{ name: 'Парковки Владивостока', category: 'auto', price: 0, logo: 'platnye-parkovki', domain: 'vladivostok.ru', period: 'month' },
{ name: 'Парковки Калуги', category: 'auto', price: 0, logo: 'platnye-parkovki', domain: 'kaluga.ru', period: 'month' },
{ name: 'Парковки Белгорода', category: 'auto', price: 0, logo: 'platnye-parkovki', domain: 'bel.ru', period: 'month' },
{ name: 'Парковки Новороссийска', category: 'auto', price: 0, logo: 'platnye-parkovki', domain: 'nvrsk.ru', period: 'month' },
{ name: 'ОСАГО онлайн', category: 'auto', price: 0, logo: 'podryad', domain: 'osago.ru', period: 'month' },
// === МЕДИЦИНА (15) ===
{ name: 'МЕДСИ', category: 'other', price: 0, logo: 'podryad', domain: 'medsi.ru', period: 'year' },
{ name: 'Доктор', category: 'other', price: 0, logo: 'podryad', domain: 'doctor.ru', period: 'month' },
{ name: 'СМ-Клиника', category: 'other', price: 0, logo: 'podryad', domain: 'smclinic.ru', period: 'month' },
{ name: 'ABC-Медицина', category: 'other', price: 0, logo: 'podryad', domain: 'abc-medicina.com', period: 'month' },
{ name: 'Клиника академика Ройтберга', category: 'other', price: 0, logo: 'podryad', domain: 'clinic.ru', period: 'month' },
{ name: 'ЗдравСити', category: 'other', price: 0, logo: 'podryad', domain: 'zdravcity.ru', period: 'month' },
{ name: 'Инвитро', category: 'other', price: 0, logo: 'podryad', domain: 'invitro.ru', period: 'month' },
{ name: 'Гемотест', category: 'other', price: 0, logo: 'podryad', domain: 'gemotest.ru', period: 'month' },
{ name: 'Хеликс', category: 'other', price: 0, logo: 'podryad', domain: 'helix.ru', period: 'month' },
{ name: 'KDL', category: 'other', price: 0, logo: 'podryad', domain: 'kdl.ru', period: 'month' },
{ name: 'СберЗдоровье', category: 'other', price: 0, logo: 'sberzdorovye', domain: 'sberhealth.ru', period: 'month' },
{ name: 'Доктор рядом', category: 'other', price: 0, logo: 'podryad', domain: 'dr.ru', period: 'month' },
{ name: 'Онлайн-консультации', category: 'other', price: 0, logo: 'podryad', domain: 'online-doctor.ru', period: 'month' },
{ name: 'ДМС подписки', category: 'other', price: 0, logo: 'podryad', domain: 'dms.ru', period: 'year' },
{ name: 'ВТБ Медицина', category: 'other', price: 0, logo: 'vtb-privilegiya', domain: 'vtb.ru', period: 'month' },
// === ТВ И РАДИО (10) ===
{ name: 'Триколор ТВ', category: 'video', price: 0, logo: 'tricolor', domain: 'tricolor.tv', period: 'year' },
{ name: 'НТВ-Плюс', category: 'video', price: 0, logo: 'ntv-plyus', domain: 'ntvplus.ru', period: 'month' },
{ name: 'МТС ТВ', category: 'video', price: 0, logo: 'mts-tv', domain: 'mts.ru', period: 'month' },
{ name: 'Ростелеком ТВ', category: 'video', price: 0, logo: 'rostelecom', domain: 'rt.ru', period: 'month' },
{ name: 'Дом.ру ТВ', category: 'video', price: 0, logo: 'domru', domain: 'domru.ru', period: 'month' },
{ name: 'Билайн ТВ', category: 'video', price: 0, logo: 'bilayn-dom', domain: 'beeline.ru', period: 'month' },
{ name: 'Okko ТВ', category: 'video', price: 0, logo: 'okko', domain: 'okko.tv', period: 'month' },
{ name: 'Wink ТВ', category: 'video', price: 0, logo: 'wink', domain: 'wink.ru', period: 'month' },
{ name: 'Смотрёшка', category: 'video', price: 0, logo: 'podryad', domain: 'smotreshka.tv', period: 'month' },
{ name: 'Edem TV', category: 'video', price: 0, logo: 'podryad', domain: 'edem.tv', period: 'month' },
// === МАГАЗИНЫ (12) ===
{ name: 'Ozon Premium', category: 'other', price: 199, logo: 'ozon-premium', domain: 'ozon.ru', period: 'month' },
{ name: 'Wildberries Premium', category: 'other', price: 0, logo: 'wildberries-prime', domain: 'wildberries.ru', period: 'month' },
{ name: 'СберСпасибо', category: 'other', price: 0, logo: 'sberpraym', domain: 'sber.ru', period: 'month' },
{ name: 'Tinkoff Pro', category: 'other', price: 0, logo: 'tbank', domain: 'tinkoff.ru', period: 'month' },
{ name: 'AliExpress Premium', category: 'other', price: 0, logo: 'aliexpress-premium', domain: 'aliexpress.ru', period: 'month' },
{ name: 'Lamoda Premium', category: 'other', price: 0, logo: 'lamoda-premium', domain: 'lamoda.ru', period: 'month' },
{ name: 'Gold Apple Box', category: 'other', price: 0, logo: 'goldapple-box', domain: 'goldapple.ru', period: 'month' },
{ name: 'Четыре Лапы', category: 'other', price: 0, logo: 'chetyre-lapy', domain: '4lapy.ru', period: 'month' },
{ name: 'ЛЭтуаль', category: 'other', price: 0, logo: 'podryad', domain: 'letu.ru', period: 'month' },
{ name: 'Рив Гош', category: 'other', price: 0, logo: 'podryad', domain: 'rigoshop.ru', period: 'month' },
{ name: 'Подружка', category: 'other', price: 0, logo: 'podryad', domain: 'podryzhka.ru', period: 'month' },
// === СОЦИАЛЬНЫЕ СЕТИ (8) ===
{ name: 'Telegram Premium', category: 'other', price: 299, logo: 'telegram-premium', domain: 'telegram.org', period: 'month' },
{ name: 'VK Combo', category: 'other', price: 0, logo: 'vk-combo', domain: 'vk.com', period: 'month' },
{ name: 'VK Premium', category: 'other', price: 0, logo: 'vk-premium', domain: 'vk.com', period: 'month' },
{ name: 'VK Play Cloud', category: 'other', price: 0, logo: 'vk-play-cloud', domain: 'vkplay.ru', period: 'month' },
{ name: 'WhatsApp Business', category: 'other', price: 0, logo: 'podryad', domain: 'whatsapp.com', period: 'month' },
{ name: 'Viber Pro', category: 'other', price: 0, logo: 'podryad', domain: 'viber.com', period: 'month' },
{ name: 'Slack Pro', category: 'other', price: 0, logo: 'podryad', domain: 'slack.com', period: 'month' },
{ name: 'Discord', category: 'other', price: 0, logo: 'discord', domain: 'discord.com', period: 'month' },
// === ДИЗАЙН И ТВОРЧЕСТВО (10) ===
{ name: 'Canva Pro', category: 'other', price: 0, logo: 'canva-pro', domain: 'canva.com', period: 'month' },
{ name: 'Figma Professional', category: 'other', price: 0, logo: 'figma', domain: 'figma.com', period: 'month' },
{ name: 'Adobe Creative Cloud', category: 'other', price: 0, logo: 'adobe-creative-cloud', domain: 'adobe.com', period: 'month' },
{ name: 'Photoshop', category: 'other', price: 0, logo: 'podryad', domain: 'adobe.com', period: 'month' },
{ name: 'Illustrator', category: 'other', price: 0, logo: 'podryad', domain: 'adobe.com', period: 'month' },
{ name: 'After Effects', category: 'other', price: 0, logo: 'podryad', domain: 'adobe.com', period: 'month' },
{ name: 'Premiere Pro', category: 'other', price: 0, logo: 'premier', domain: 'adobe.com', period: 'month' },
{ name: 'InDesign', category: 'other', price: 0, logo: 'podryad', domain: 'adobe.com', period: 'month' },
{ name: 'Lightroom', category: 'other', price: 0, logo: 'podryad', domain: 'adobe.com', period: 'month' },
{ name: 'CorelDRAW', category: 'other', price: 0, logo: 'podryad', domain: 'coreldraw.com', period: 'month' },
// === ИИ И НЕЙРОСЕТИ (10) ===
{ name: 'ChatGPT Plus', category: 'other', price: 1900, logo: 'chatgpt-plus', domain: 'openai.com', period: 'month' },
{ name: 'Midjourney', category: 'other', price: 0, logo: 'midjourney', domain: 'midjourney.com', period: 'month' },
{ name: 'Claude Pro', category: 'other', price: 0, logo: 'claude-pro', domain: 'anthropic.com', period: 'month' },
{ name: 'Perplexity Pro', category: 'other', price: 1900, logo: 'perplexity-pro', domain: 'perplexity.ai', period: 'month' },
{ name: 'DeepSeek Pro', category: 'other', price: 0, logo: 'deepseek-pro', domain: 'deepseek.com', period: 'month' },
{ name: 'GigaChat Pro', category: 'other', price: 0, logo: 'gigachat-pro', domain: 'sberbank.ru', period: 'month' },
{ name: 'Kandinsky', category: 'other', price: 0, logo: 'podryad', domain: 'fusionbrain.ai', period: 'month' },
{ name: 'YandexGPT', category: 'other', price: 0, logo: 'yandeks-plyus', domain: 'yandex.ru', period: 'month' },
{ name: 'NeuralHire', category: 'other', price: 0, logo: 'podryad', domain: 'neuralhire.com', period: 'month' },
{ name: 'NovelAI', category: 'other', price: 0, logo: 'podryad', domain: 'novelai.net', period: 'month' },
// === БИЗНЕС И ПРОДУКТИВНОСТЬ (15) ===
{ name: 'Notion Plus', category: 'other', price: 0, logo: 'notion', domain: 'notion.so', period: 'month' },
{ name: 'Trello Premium', category: 'other', price: 0, logo: 'podryad', domain: 'trello.com', period: 'month' },
{ name: 'Asana Premium', category: 'other', price: 0, logo: 'podryad', domain: 'asana.com', period: 'month' },
{ name: 'Monday.com', category: 'other', price: 0, logo: 'podryad', domain: 'monday.com', period: 'month' },
{ name: 'ClickUp', category: 'other', price: 0, logo: 'podryad', domain: 'clickup.com', period: 'month' },
{ name: 'Airtable', category: 'other', price: 0, logo: 'podryad', domain: 'airtable.com', period: 'month' },
{ name: 'Miro Pro', category: 'other', price: 0, logo: 'podryad', domain: 'miro.com', period: 'month' },
{ name: 'Zoom Pro', category: 'other', price: 0, logo: 'podryad', domain: 'zoom.us', period: 'month' },
{ name: 'Microsoft 365 Family', category: 'other', price: 0, logo: 'microsoft-365-family', domain: 'microsoft.com', period: 'month' },
{ name: 'Microsoft 365 Personal', category: 'other', price: 0, logo: 'microsoft-365-personal', domain: 'microsoft.com', period: 'month' },
{ name: 'Google Workspace', category: 'other', price: 0, logo: 'google-one-100gb', domain: 'workspace.google.com', period: 'month' },
{ name: 'Яндекс 360', category: 'other', price: 0, logo: 'yandeks-plyus', domain: '360.yandex.ru', period: 'month' },
{ name: 'VK WorkSpace', category: 'other', price: 0, logo: 'vk', domain: 'vk.com', period: 'month' },
{ name: 'Битрикс24', category: 'other', price: 0, logo: 'podryad', domain: 'bitrix24.ru', period: 'month' },
{ name: 'amoCRM', category: 'other', price: 0, logo: 'podryad', domain: 'amocrm.ru', period: 'month' },
// === РАЗВЛЕЧЕНИЯ (10) ===
{ name: 'Tinder Plus', category: 'other', price: 0, logo: 'podryad', domain: 'tinder.com', period: 'month' },
{ name: 'Bumble Premium', category: 'other', price: 0, logo: 'podryad', domain: 'bumble.com', period: 'month' },
{ name: 'Mamba VIP', category: 'other', price: 0, logo: 'mamba-vip', domain: 'mamba.ru', period: 'month' },
{ name: 'Pure Premium', category: 'other', price: 0, logo: 'podryad', domain: 'pure.app', period: 'month' },
{ name: 'Leomax Premium', category: 'other', price: 0, logo: 'podryad', domain: 'leomax.ru', period: 'month' },
{ name: 'Boosty Premium', category: 'other', price: 0, logo: 'podryad', domain: 'boosty.to', period: 'month' },
{ name: 'Patreon', category: 'other', price: 0, logo: 'podryad', domain: 'patreon.com', period: 'month' },
{ name: 'DonationAlerts', category: 'other', price: 0, logo: 'podryad', domain: 'donationalerts.com', period: 'month' },
{ name: 'YouTube Memberships', category: 'other', price: 0, logo: 'youtube-music', domain: 'youtube.com', period: 'month' },
{ name: 'Twitch Turbo', category: 'other', price: 0, logo: 'twich', domain: 'twitch.tv', period: 'month' },
// === НОВОСТИ И СМИ (8) ===
{ name: 'Коммерсантъ', category: 'other', price: 0, logo: 'kommersant', domain: 'kommersant.ru', period: 'month' },
{ name: 'Ведомости', category: 'other', price: 0, logo: 'vedomosti', domain: 'vedomosti.ru', period: 'month' },
{ name: 'РБК Pro', category: 'other', price: 0, logo: 'podryad', domain: 'rbk.ru', period: 'month' },
{ name: 'Forbes', category: 'other', price: 0, logo: 'podryad', domain: 'forbes.ru', period: 'month' },
{ name: 'Esquire', category: 'other', price: 0, logo: 'podryad', domain: 'esquire.ru', period: 'month' },
{ name: 'Афиша Premium', category: 'other', price: 0, logo: 'podryad', domain: 'afisha.ru', period: 'month' },
{ name: 'The Village', category: 'other', price: 0, logo: 'podryad', domain: 'the-village.ru', period: 'month' },
{ name: 'VC.ru Premium', category: 'other', price: 0, logo: 'podryad', domain: 'vc.ru', period: 'month' },
// === ПРОЧЕЕ (30) ===
{ name: 'SMS уведомления', category: 'other', price: 0, logo: 'sms', domain: '', period: 'month' },
{ name: 'Push уведомления', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'Голосовая почта', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'Виртуальный номер', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'Алиса', category: 'other', price: 0, logo: 'yandeks-plyus', domain: 'yandex.ru', period: 'month' },
{ name: 'Маруся', category: 'other', price: 0, logo: 'vk', domain: 'vk.com', period: 'month' },
{ name: 'Яндекс Навигатор', category: 'other', price: 0, logo: 'yandeksdrayv-plus', domain: 'yandex.ru', period: 'month' },
{ name: 'Погода Premium', category: 'other', price: 0, logo: 'podryad', domain: 'yandex.ru', period: 'month' },
{ name: 'Переводчик Premium', category: 'other', price: 0, logo: 'podryad', domain: 'translate.yandex.ru', period: 'month' },
{ name: 'Антивирус Premium', category: 'other', price: 0, logo: 'kaspersky', domain: 'kaspersky.ru', period: 'year' },
{ name: 'VPN сервис', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'Прокси сервис', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'Timeweb', category: 'other', price: 0, logo: 'podryad', domain: 'timeweb.ru', period: 'month' },
{ name: 'Reg.ru', category: 'other', price: 0, logo: 'podryad', domain: 'reg.ru', period: 'month' },
{ name: 'Beget', category: 'other', price: 0, logo: 'podryad', domain: 'beget.com', period: 'month' },
{ name: 'SSL сертификаты', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'year' },
{ name: 'Email хостинг', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'CRM системы', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'ERP системы', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'Бухгалтерия онлайн', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'Юридические сервисы', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'Налоговые сервисы', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'Кадровые сервисы', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'Рекламные платформы', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'Аналитические сервисы', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'Маркетинговые платформы', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'Email рассылки', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'SMS рассылки', category: 'other', price: 0, logo: 'sms', domain: '', period: 'month' },
{ name: 'Чат-боты', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
{ name: 'Виджеты на сайт', category: 'other', price: 0, logo: 'podryad', domain: '', period: 'month' },
// === ЖКХ И ГОС (3) ===
{ name: 'ЖКХ', category: 'other', price: 0, logo: 'zhkh', domain: '', period: 'month' },
{ name: 'Взнос СНТ', category: 'other', price: 0, logo: 'snt', domain: '', period: 'year' },
{ name: 'Штрафы ГИБДД', category: 'other', price: 0, logo: 'shtrafy-gibdd', domain: 'gibdd.ru', period: 'month' }
].sort((a, b) => a.name.localeCompare(b.name, 'ru'));